### ISSUE TITLE
DLK

### ISSUE THREAD

**Issue by tnhaider** [realjanpaulus/german-corpora#1]
Hi Jan,

Wie bist du denn mit den ids für Gedichte in DLK umgegangen?

Version 3 taugt nämlich eher nur was für Strophen, weil nur Strophenduplikate entfernt wurden. Wenn du nur die poem_ids nimmst, dann müssten da einige fragmentierte Gedichte rauskommen.

Version 4 hat diese Probleme nicht mehr. 

Wir schauen auch gerade, wie wir die Gutenberg-DE Sammlung mitaufnehmen.
Da müssten noch ein paar tausend Texte dazukommen.

Beste Grüße,
Thomas

**Comment by realjanpaulus** [comment]
Hi Thomas,

ich sehe gerade, dass das Gedichts-Korpus gar nicht im "corpora"-Ordner vorhanden ist (müsste nun vorhanden sein). Die IDs habe ich tatsächlich entfernt. Alle Strophen wurden anhand des Gedichts-Titels zu einem Gedicht zusammengefügt, die Strophen sind dementsprechend unsortiert (habe ich in der README ergänzt).  Ich habe aber geplant, dass die Tage zu aktualisieren und eine Spalte mit den IDs hinzuzfügen sowie die Strophen zu sortieren. Weißt du zufällig, ob die Lizenz für euer Korpus folgende ist: (CC BY 4.0)? Dann würde ich diese nämlich noch hinzufügen.

**Comment by tnhaider** [comment]
Ja, nur wenn du Version 3 nimmst, dann kommen da mehr Gedichte dabei raus, als es tatsächlich sind. Ein Gedicht kann dann über 1--5 ids verteilt sein, weil die poem_ids nicht mehr zusammenpassen (weil Duplikate auf Strophenebene entfernt wurden).

Wie gesagt, in Version 4 ist das behoben. Wenn du also Experimente auf Gedichtebene drauf machen willst, würde ich Version 4 empfehlen.

Grüße,
Thomas

**Comment by realjanpaulus** [comment]
Danke für den Tipp. Ich bin gerade dabei, dass Skript `texts_to_csv.py` auf Version 4 anzupassen, diesmal inklusive IDs und Reihenfolge.

**Comment by realjanpaulus** [comment]
Das Paper werde ich verlinken. Die Daten verwende ich nur für persönliche Zwecke, zur wissenschaftliche Bearbeitung für Hausarbeiten und für als Beispiel für Uni-Kurse. Die Idee vom Repository ist, csv-Dateien von deutschen Korpora für die Nutzung für Machine Learning/Deep Learning bereitzustellen und interessante Korpora (wie euer Korpus) meinen Kommilitonen bekannter zu machen :)
